### ISSUE TITLE
Dark theme bugs

### ISSUE THREAD

**Issue by VasilisKos** [foxtrotdev/learn-digits#3]
There are some UI bugs in the dark theme:
1. At the top of the plant picture, the black ribbon with the name of the tab (Home, Game, About) remains after starting the game. In the light theme it disappears as supposed to.
2. The top edge of the buttons area remains white when in dark mode. That should be black, like the rest.
3. The notifications area should have that light purple color of the number buttons, not the darker one of the light theme. 

I attach a white and a dark theme screenshot that spot the differences.

![Screenshot_20230609-091253](https://github.com/foxtrotdev/learn-digits/assets/12777771/bca2c687-b21e-4ca0-bca6-8176490d2e47)

![Screenshot_20230609-091156_1](https://github.com/foxtrotdev/learn-digits/assets/12777771/8ff36686-1147-4827-863e-9b22ec9904fc)

**Comment by foxtrotdev** [comment]
Thanks. Provided the fix.

**Comment by VasilisKos** [comment]
Number 3 was not fixed though. Anyway, not a big deal. Thanks. 😉
