### ISSUE TITLE
Persian voice

### ISSUE THREAD

**Issue by xmha97** [foxtrotdev/learn-digits#5]
Hi,
My language is Persian.
Please add the multi-language-voice feature.

**Comment by foxtrotdev** [comment]
I am afraid I cannot do that. I don't speak Persian. You can provide PR with voice pack and updated strings.

**Comment by xmha97** [comment]
I know.
I sent you Persian voices.
If you add language support.

**Comment by foxtrotdev** [comment]
It becomes to be supported after I provide voice and text.
